apiVersion: v1 
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
     app: myrc
  template:
     metadata:
       labels: 
         app: myrc
     spec: 
       containers:
       - name: con1
         image: nginx:latest
         ports:
         - containerPort: 80
           
