apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devrole
  namespace: devops
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
