apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devrole-bind
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devrole
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: devops
