apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mango
  name: secret-pod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    env:
    - name: pass
      valueFrom:
        secretKeyRef:
          name: mypass
          key: PASSWORD
    - name: ENV
      value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: mywp1
spec:
  type: NodePort
  selector:
     app: wordpress
  ports:
  - port: 80
    nodePort: 30123 

